### ISSUE TITLE
Make input files

### ISSUE THREAD

**Issue by shenlinyong** [OluwadareLab/ChromeBat#1]
This software is really great, but I don't know how to prepare my input file? How should I make the `N by N intra-chromosomal contact matrix` from `.HiC `, `cool` or `h5` format HiC file?

**Comment by OluwadareLab** [comment]
> This software is really great, but I don't know how to prepare my input file? How should I make the `N by N intra-chromosomal contact matrix` from `.HiC `, `cool` or `h5` format HiC file?

Thanks for using our tool. Generally obtaining a Nx N matrix from these formats might be possible directly or may require a couple of steps depending on the format.  Below are example steps you could follow to achieve this for each format:

 ***.hic format:***  (1) Use the `Dump` function from Juicer tools created by Aidenlabs. This will generally extract the data as a sparse matrix format (2) Convert the sparse matrix to a full matrix. For this step, you can write your own code for this or just use the HiCcompare library `sparse2full` function.

***.cool format:​*** (1) Use the cooler tool  `dump` function to extract data. This function usually just extracts but might not be in a usable format yet. (2) Next,  Create a sparse, three-column, matrix or a full NxN matrix from the extracted data. To go from this extracted data to the usable sparse, three-column, matrix or a full NxN matrix, you will need to write a customized script to do the data formatting. We are not certain if there is a publicly available script to do this.
*Alternatively​,*<br /> HiCcompare has a function `[cooler2sparse](https://rdrr.io/bioc/HiCcompare/man/cooler2sparse.html)`, it might be worth exploring as well, as the documentation says it can Transform a .cool file to a sparse upper triangular matrix. Of course, if this works, you can just use there `sparse2full` function to convert to a NxN full matrix.


_**.h5​:**_ Getting data from the h5 format is trickier than the formats above.  (1) You can convert the .h5 file to a cool format file by using the `hicConvertFormat` function from the HiCExplorer tools library. (2) Now that your data is in cool format, you can follow the instruction for the cool format above.

That said, the datasets used in our experiments in the ChromeBat data were already in the NxN format, so we did not go through the steps above.

We hope that you find these recommendations helpful.

**Comment by shenlinyong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much!
        
    
    
        Your answer is really great, but with these methods of yours, I can only get the npy matrix of interactions within one chromosome, or the npy matrix of interactions between two chromosomes. I want to draw a 3D resultant model of the whole chromosome (focusing on the specific 3D position of the chromosome in the true whole genome), not just the 3D spatial structure of one chromosome, what should I add?
        
    Thank you very much!
    
     
    
        
                    
        
    
 

    On 6/30/2022 00:00，Oluwadare ***@***.***> wrote： 






This software is really great, but I don't know how to prepare my input file? How should I make the N by N intra-chromosomal contact matrix from .HiC , cool or h5 format HiC file?



Thanks for using our tool. Generally obtaining a Nx N matrix from these formats might be possible directly or may require a couple of steps depending on the format.  Below are example steps you could follow to achieve this for each format:

.hic format:  (1) Use the Dump function from Juicer tools created by Aidenlabs. This will generally extract the data as a sparse matrix format (2) Convert the sparse matrix to a full matrix. For this step, you can write your own code for this or just use the HiCcompare library sparse2full function.

.cool format: (1) Use the cooler tool  dump function to extract data. This function usually just extracts but might not be in a usable format yet. (2) Next,  Create a sparse, three-column, matrix or a full NxN matrix from the extracted data. To go from this extracted data to the usable sparse, three-column, matrix or a full NxN matrix, you will need to write a customized script to do the data formatting. We are not certain if there is a publicly available script to do this.

Alternatively, HiCcompare has a function [cooler2sparse](https://rdrr.io/bioc/HiCcompare/man/cooler2sparse.html), it might be worth exploring as well, as the documentation says it can Transform a .cool file to a sparse upper triangular matrix. Of course, if this works, you can just use there sparse2full` function to convert to a NxN full matrix.

.h5: Getting data from the h5 format is trickier than the formats above.  (1) You can convert the .h5 file to a cool format file by using the hicConvertFormat function from the HiCExplorer tools library. (2) Now that your data is in cool format, you can follow the instruction for the cool format above.

That said, the datasets used in our experiments in the ChromeBat data were already in the NxN format, so we did not go through the steps above.

We hope that you find these recommendations helpful.

**Comment by OluwadareLab** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Thank you very much! Your answer is really great, but with these methods of yours, I can only get the npy matrix of interactions within one chromosome, or the npy matrix of interactions between two chromosomes. I want to draw a 3D resultant model of the whole chromosome (focusing on the specific 3D position of the chromosome in the true whole genome), not just the 3D spatial structure of one chromosome, what should I add? Thank you very much! On 6/30/2022 00:00，Oluwadare ***@***.***> wrote： This software is really great, but I don't know how to prepare my input file? How should I make the N by N intra-chromosomal contact matrix from .HiC , cool or h5 format HiC file? Thanks for using our tool. Generally obtaining a Nx N matrix from these formats might be possible directly or may require a couple of steps depending on the format. Below are example steps you could follow to achieve this for each format: .hic format: (1) Use the Dump function from Juicer tools created by Aidenlabs. This will generally extract the data as a sparse matrix format (2) Convert the sparse matrix to a full matrix. For this step, you can write your own code for this or just use the HiCcompare library sparse2full function. .cool format: (1) Use the cooler tool dump function to extract data. This function usually just extracts but might not be in a usable format yet. (2) Next, Create a sparse, three-column, matrix or a full NxN matrix from the extracted data. To go from this extracted data to the usable sparse, three-column, matrix or a full NxN matrix, you will need to write a customized script to do the data formatting. We are not certain if there is a publicly available script to do this. Alternatively, HiCcompare has a function [cooler2sparse](https://rdrr.io/bioc/HiCcompare/man/cooler2sparse.html), it might be worth exploring as well, as the documentation says it can Transform a .cool file to a sparse upper triangular matrix. Of course, if this works, you can just use there sparse2full` function to convert to a NxN full matrix. .h5: Getting data from the h5 format is trickier than the formats above. (1) You can convert the .h5 file to a cool format file by using the hicConvertFormat function from the HiCExplorer tools library. (2) Now that your data is in cool format, you can follow the instruction for the cool format above. That said, the datasets used in our experiments in the ChromeBat data were already in the NxN format, so we did not go through the steps above. We hope that you find these recommendations helpful. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I am not sure I understand your question; However from what I can infer:
Chromebat focuses on reconstruction based on the Hi-C Matrix provided. Be it for an intra-chromosome interaction frequency matrix or an inter-chromosome interaction frequency matrix. Essentially, it will construct a 3D structure based on the input Hi-C input data. As an example,  If you are interested in reconstructing a specific region, you will only need to provide that region data Hi-C Matrix as input only.
However, it might have difficulty constructing an entire genome, which consists of multiple chromosomes, because this was not taken into account in the tool/algorithm reconstruction. You can access our code and see how you can adapt or improve it for your specific problem.
